// *** This is a generated file; if you want to change it, please change the generator or the appropriate interface file
// 
// This file was generated by NetworkProxyBuilder, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 

namespace OSMP.NetworkInterfaces
{
public class LockRpcToClient_ClientProxy : OSMP.NetworkInterfaces.ILockRpcToClient
{
   RpcController rpc;
   object connection;

   public LockRpcToClient_ClientProxy( RpcController rpc, object connection )
   {
      this.rpc = rpc;
      this.connection = connection;
   }
   public void LockRequestResponse( System.Object netconnection, OSMP.NetworkInterfaces.IReplicated targetobject, System.Boolean LockCreated )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToClient", "LockRequestResponse",  new object[]{ netconnection, targetobject, LockCreated } );
   }
   public void LockReleased( System.Object netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToClient", "LockReleased",  new object[]{ netconnection, targetobject } );
   }
}
}
