// *** This is a generated file; if you want to change it, please change the generator or the appropriate interface file
// 
// This file was generated by NetworkProxyBuilder, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 

namespace OSMP.NetworkInterfaces
{
public class LockRpcToServer_ClientProxy : OSMP.NetworkInterfaces.ILockRpcToServer
{
   RpcController rpc;
   object connection;

   public LockRpcToServer_ClientProxy( RpcController rpc, object connection )
   {
      this.rpc = rpc;
      this.connection = connection;
   }
   public void RequestLock( System.Object netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "RequestLock",  new object[]{ netconnection, targetobject } );
   }
   public void RenewLock( System.Object netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "RenewLock",  new object[]{ netconnection, targetobject } );
   }
   public void ReleaseLock( System.Object netconnection, OSMP.NetworkInterfaces.IReplicated targetobject )
   {
      rpc.SendRpc( connection, "OSMP.NetworkInterfaces.ILockRpcToServer", "ReleaseLock",  new object[]{ netconnection, targetobject } );
   }
}
}
