// *** This is a generated file; if you want to change it, please change the generator or the appropriate interface file
// 
// This file was generated by NetworkProxyBuilder, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 

namespace OSMP.Testing
{
public class TestInterface_ServerWrapper
{
   object connection;

   public TestInterface_ServerWrapper( object connection )
   {
      this.connection = connection;
   }
   public void SayHello( object[] parameters )
   {
      new TestInterface( connection ).SayHello(  );
   }
   public void SayMessage( object[] parameters )
   {
      new TestInterface( connection ).SayMessage( ( System.String )parameters[0] );
   }
   public void SendObject( object[] parameters )
   {
      new TestInterface( connection ).SendObject( ( OSMP.Testing.TestClass )parameters[0] );
   }
}
}
